import Head from 'next/head';

export default function Board() {
  return (
    <>
      <Head>
        <title>판다마켓 - 자유게시판</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="mt-[100px]">
        <h1>베스트 게시글</h1>
        <div></div>
      </div>
      <div>
        <h1>게시글</h1>
        <div></div>
      </div>
    </>
  );
}
